blank_issues_enabled: false
contact_links:
- name: Feature Requests or Ideas
    url: https://github.com/spencerlabs/utils/discussions/categories/ideas
    about: Please discuss feature requests and ideas here.
