name: Publish Package to npm
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - if: github.event.release.prerelease
        name: Get version number
        id: version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "version=${VERSION:1}" >> $GITHUB_OUTPUT

      - if: github.event.release.prerelease
        name: Prerelease
        run: |
          npm pkg set version=${{ steps.version.outputs.version }}

      - run: yarn
      - run: yarn build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
